version: '3.7'

services:
    nas:
        image: dperson/samba:rpi
        container_name: nas
        volumes:
            - /mnt/portable_ssd/storage:/mnt/storage_space
        environment:
            TZ: 'Asia/Tokyo'
            USERID: '65534'
        networks:
            - frontend
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"
        tmpfs:
            - /tmp
        restart: always
        stdin_open: true
        tty: true
        command: '-s "storage;/mnt/storage_space;yes;no;yes;all;none;*;NAS on Raspberry Pi"'

networks:
    frontend:
        name: frontend_network
