version: '3.7'

x-logging:
    &json-logging
    driver: json-file
    options:
        max-size: "1m"
        max-file: "3"

services:
    #nas:
    #    image: dperson/samba:rpi
    #    container_name: nas
    #    volumes:
    #        - /mnt/portable_ssd/storage:/mnt/storage_space
    #    environment:
    #        TZ: 'Asia/Tokyo'
    #        USERID: '65534'
    #    networks:
    #        - frontend
    #    ports:
    #        - "137:137/udp"
    #        - "138:138/udp"
    #        - "139:139/tcp"
    #        - "445:445/tcp"
    #    tmpfs:
    #        - /tmp
    #    restart: always
    #    stdin_open: true
    #    tty: true
    #    command: '-s "storage;/mnt/storage_space;yes;no;yes;all;none;*;NAS on Raspberry Pi"'

    infrared_controller:
        build:
            context: ./infrared_controller
            dockerfile: Dockerfile
            args:
                TZ: 'Asia/Tokyo'
        image: custom_infrared_controller
        container_name: infrared_controller
        volumes:
            - ./infrared_controller/src:/infrared_controller:ro
        environment:
            - HTTP_PORT=8180
        networks:
            - middle
        expose:
            - 8180
        restart: always
        logging: *json-logging
        devices:
            - /dev/i2c-1:/dev/i2c-1

    nodered:
        build:
            context: ./nodered
            dockerfile: Dockerfile
        image: custom_nodered
        container_name: nodered
        volumes:
            - ./nodered/data:/data
        environment:
            - PORT=1880
            - TZ=Asia/Tokyo
            - FLOWS=/data/flows.json
        networks:
            - frontend
            - middle
        ports:
            - 1880:1880
        restart: always
        logging: *json-logging

networks:
    frontend:
        name: frontend_network
    middle:
        name: middle_network
